### ISSUE TITLE
Authentication method fails on current Fortify SSC release

### ISSUE THREAD

**Issue by xolian** [target/fortifyapi#10]
Authentication fails on current Fortify SSC release.
Create 17.20 Fortify SSC Authentication Method

- [ ] Fortify SSC has changed endpoint from  `/{SSC Server Context}/api/v1/auth/obtain_token` to   `/{SSC Server Context}/api/v1/tokens `.

Current authentication fails from the 17.10 implementation. Additionally, type `UnifiedLoginToken` name has been introduced.

**Comment by attesch** [comment]
In my testing I found that the 17.10 endpoint api/v1/auth/obtain_token will still work to acquire a token from 17.20.  This is no longer documented, but this issue should not prevent moving to SSC 17.20

**Comment by xolian** [comment]
No updates made to auth until methods are deleted, per Aaron's comment
